#########################################################################
# Title:         Cloudbox: Portainer Role                               #
# Author(s):     l3uddz                                                 #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  portainer/portainer                                    #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Create DNS Record
  include_role:
    name: dns
  vars:
    record: portainer

- name: Stop and remove any existing container
  docker_container:
    name: portainer
    state: absent

- name: Create portainer directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/portainer

- name: Create and start container
  docker_container:
    name: portainer
    image: "portainer/portainer"
    pull: yes
    published_ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - "/opt/portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      VIRTUAL_HOST: "portainer.{{ user.domain }}"
      VIRTUAL_PORT: "9000"
      LETSENCRYPT_HOST: "portainer.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
      TZ: "{{ tz }}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - portainer
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
